-- Supabase advisory: "RLS Disabled in Public: public.spatial_ref_sys"
--
-- ⚠️ SAFE TO IGNORE — there is NOTHING to run here.
--
-- `spatial_ref_sys` is a static PostGIS reference table (a lookup of map
-- coordinate-system / projection definitions). It is created and owned by
-- the PostGIS extension, holds NO user data, and is read-only reference
-- material. RLS exists to protect user rows; this table has none to protect.
--
-- You CANNOT enable RLS on it from the SQL editor — it returns:
--     ERROR: 42501: must be owner of table spatial_ref_sys
-- because Supabase (not your project role) owns it. This is expected on
-- every Supabase project that uses PostGIS.
--
-- Action: dismiss / ignore this specific advisory in the Supabase dashboard.
-- It is not a real security issue for ORBII.
